version: '2'
services:
  rockstock-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/rockstock/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=rockstock
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
